# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            I am a website. Hear me roar.
tagline:          'A Tagline Is Me'
description:      'I am a description. OMG I am describing some stuff.' 
url:              https://github.com/jrdawson758/website
baseurl:          /

author:
  name:           'Jo Dawson'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
